export const REQUESTING_ACCESS_TOKEN = 'REQUESTING_ACCESS_TOKEN'
export const REQUEST_ACCESS_TOKEN_SUCCEEDED = 'REQUEST_ACCESS_TOKEN_SUCCEEDED'
export const REQUEST_ACCESS_TOKEN_FAILED = 'REQUEST_ACCESS_TOKEN_FAILED'
