export const REQUESTING_ACCESS_TOKEN = 'REQUESTING_ACCESS_TOKEN'
export const REQUEST_ACCESS_TOKEN_SUCCEEDED = 'REQUEST_ACCESS_TOKEN_SUCCEEDED'
export const REQUEST_ACCESS_TOKEN_FAILED = 'REQUEST_ACCESS_TOKEN_FAILED'

export const CACHE_ACCESS_TOKEN_SUCCEEDED = 'CACHE_ACCESS_TOKEN_SUCCEEDED'
export const CACHE_ACCESS_TOKEN_FAILED = 'CACHE_ACCESS_TOKEN_FAILED'

export const GET_ACCESS_TOKEN_SUCCEEDED = 'GET_ACCESS_TOKEN_SUCCEEDED'
export const GET_ACCESS_TOKEN_FAILED = 'GET_ACCESS_TOKEN_FAILED'
