export const REQUEST_ACCESS_START = 'REQUEST_ACCESS_START'
export const REQUEST_ACCESS_TOKEN_SUCCEEDED = 'REQUEST_ACCESS_TOKEN_SUCCEEDED'
export const REQUEST_ACCESS_TOKEN_FAILED = 'REQUEST_ACCESS_TOKEN_FAILED'
