export const REQUESTING_USER_MEDIA = 'REQUESTING_USER_MEDIA'
export const REQUEST_USER_MEDIA_SUCCEEDED = 'REQUEST_USER_MEDIA_SUCCEEDED'
export const REQUEST_USER_MEDIA_FAILED = 'REQUEST_USER_MEDIA_FAILED'
