export const REQUESTING_USER_INFO = 'REQUESTING_USER_INFO'
export const REQUEST_USER_INFO_SUCCEEDED = 'REQUEST_USER_INFO_SUCCEEDED'
export const REQUEST_USER_INFO_FAILED = 'REQUEST_USER_INFO_FAILED'

export const REQUESTING_USER_MEDIA = 'REQUESTING_USER_MEDIA'
export const REQUEST_USER_MEDIA_SUCCEEDED = 'REQUEST_USER_MEDIA_SUCCEEDED'
export const REQUEST_USER_MEDIA_FAILED = 'REQUEST_USER_MEDIA_FAILED'
